### ISSUE TITLE
Runtime crash

### ISSUE THREAD

**Issue by vorov2** [vorov2/dyalect#225]
**Dyalect version**
0.9.8

**Describe the bug**

```
Index was outside the bounds of the array.
```

**Comment by vorov2** [comment]
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Dyalect.Runtime.DyMachine.ExecuteWithData(DyNativeFunction function, DyObject[] locals, ExecutionContext ctx) in C:\repos\source\Dyalect\master\Dyalect\Runtime\DyMachine.cs:line 145
   at Dyalect.Runtime.DyMachine.Execute(ExecutionContext ctx) in C:\repos\source\Dyalect\master\Dyalect\Runtime\DyMachine.cs:line 23
   at Dyalect.InteractiveContext.Eval(Boolean measureTime) in C:\repos\source\Dyalect\master\Dyalect.Console\InteractiveContext.cs:line 103

**Comment by vorov2** [comment]
The error is most probably connected with the incorrect `break` statement compilation logic.
