### ISSUE TITLE
Virtual machine crush

### ISSUE THREAD

**Issue by vorov2** [vorov2/dyalect#681]
```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Dyalect.Runtime.DyMachine.ExecuteWithData(DyNativeFunction function, DyObject[] locals, ExecutionContext ctx) in C:\repos\source\dyalect\feature\Dyalect\Runtime\DyMachine.cs:line 385
   at Dyalect.Runtime.DyMachine.ExecuteModule(Int32 unitId, ExecutionContext ctx) in C:\repos\source\dyalect\feature\Dyalect\Runtime\DyMachine.cs:line 61
   at Dyalect.Runtime.DyMachine.Execute(ExecutionContext ctx) in C:\repos\source\dyalect\feature\Dyalect\Runtime\DyMachine.cs:line 21
   at Dyalect.InteractiveContext.Eval(Boolean measureTime) in C:\repos\source\dyalect\feature\Dyalect.Console\InteractiveContext.cs:line 132
   at Dyalect.InteractiveContext.EvalFile(String fileName, Boolean measureTime) in C:\repos\source\dyalect\feature\Dyalect.Console\InteractiveContext.cs:line 122
   at Dyalect.Program.Run(DyaOptions options) in C:\repos\source\dyalect\feature\Dyalect.Console\Program.cs:line 64
   at Dyalect.Program.Main(String[] args) in C:\repos\source\dyalect\feature\Dyalect.Console\Program.cs:line 26
```

code:

```swift
	for x in sequence(this, x.next is not Empty() ? x.next : nil) {
		xs = List.Cons(x.value, xs)
	}
```

**Comment by vorov2** [comment]
The following code would crush as well:

```swift
for x in 1..x {
}
```

Iteration variable is not initialized.
