### ISSUE TITLE
Critical VM failure

### ISSUE THREAD

**Issue by vorov2** [vorov2/dyalect#74]
**Dyalect version**
0.5.4

**Describe the bug**
When executing code:

```swift
var acc = 0
for x in 1..5 {
    if x % 2 != 0 {
        continue
    }
    for y in 6..10 {
        if y % 2 == 0 {
            continue
        }
        acc += x + y
    }
}
```
result:

```
Unhandled Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Dyalect.Runtime.EvalStack.Push(DyObject val) in C:\repos\source\Dyalect\feature\Dyalect\Runtime\EvalStack.cs:line 31
   at Dyalect.Runtime.DyMachine.ExecuteWithData(DyNativeFunction function, DyObject[] locals, ExecutionContext ctx) in C:\repos\source\Dyalect\feature\Dyalect\Runtime\DyMachine.cs:line 159
   at Dyalect.Runtime.DyMachine.ExecuteModule(Int32 unitId, ExecutionContext ctx) in C:\repos\source\Dyalect\feature\Dyalect\Runtime\DyMachine.cs:line 75
   at Dyalect.Runtime.DyMachine.Execute(ExecutionContext ctx) in C:\repos\source\Dyalect\feature\Dyalect\Runtime\DyMachine.cs:line 45
   at Dyalect.InteractiveContext.Eval(Boolean measureTime) in C:\repos\source\Dyalect\feature\Dyalect.Console\InteractiveContext.cs:line 99
   at Dyalect.InteractiveContext.EvalFile(String fileName, Boolean measureTime) in C:\repos\source\Dyalect\feature\Dyalect.Console\InteractiveContext.cs:line 89
   at Dyalect.Program.Main(String[] args) in C:\repos\source\Dyalect\feature\Dyalect.Console\Program.cs:line 35
```

**Comment by vorov2** [comment]
This is a bug with compound assignment. Code like so works:

```swift
var acc = 0
for x in 1..5 {
    if x % 2 != 0 {
        continue
    }
    for y in 6..10 {
        if y % 2 == 0 {
            continue
        }
        acc = acc + x + y
    }
}
```

**Comment by vorov2** [comment]
Minimal code sample to reproduce:

```swift
var acc = 0

for y in 6..10 {
    if y % 2 == 0 {
        continue
    }
    acc += 0 + y
}
```

**Comment by vorov2** [comment]
Pushed to `feature`
