### ISSUE TITLE
VM crush: Stack is corrupted

### ISSUE THREAD

**Issue by vorov2** [vorov2/dyalect#77]
**Dyalect version**
0.5.5

**Describe the bug**
The following code:

```swift
1..10
true
```

causes:

```
Unhandled Exception: Dyalect.Runtime.DyRuntimeException: Stack is corrupted.
   at Dyalect.Runtime.DyMachine.ExecuteWithData(DyNativeFunction function, DyObject[] locals, ExecutionContext ctx) in C:\repos\source\Dyalect\feature\Dyalect\Runtime\DyMachine.cs:line 117
   at Dyalect.Runtime.DyMachine.ExecuteModule(Int32 unitId, ExecutionContext ctx) in C:\repos\source\Dyalect\feature\Dyalect\Runtime\DyMachine.cs:line 75
   at Dyalect.Runtime.DyMachine.Execute(ExecutionContext ctx) in C:\repos\source\Dyalect\feature\Dyalect\Runtime\DyMachine.cs:line 45
   at Dyalect.InteractiveContext.Eval(Boolean measureTime) in C:\repos\source\Dyalect\feature\Dyalect.Console\InteractiveContext.cs:line 99
   at Dyalect.InteractiveContext.EvalFile(String fileName, Boolean measureTime) in C:\repos\source\Dyalect\feature\Dyalect.Console\InteractiveContext.cs:line 89
   at Dyalect.Program.Main(String[] args) in C:\repos\source\Dyalect\feature\Dyalect.Console\Program.cs:line 35
Press any key to continue . . .
```

**Comment by vorov2** [comment]
Pushed to `feature`
