### ISSUE TITLE
VM crush & invalid break behavior

### ISSUE THREAD

**Issue by vorov2** [vorov2/dyalect#78]
**Dyalect version**
0.5.5

**Describe the bug**
`break` behaves in a weird manner and causes VM to crush.

**To Reproduce**
```swift
for x in 1..10 {
    if x > 5 {
        print(">>1")
        break
        print(">>2")
        print(">>3")
    }
    print(x)
}
```

**Expected behavior**
Output:

```
1
2
3
4
5
>>1
```

**Actual behavior**

Output:

```
1
2
3
4
5
>>1
>>2

Unhandled Exception: Dyalect.Runtime.DyRuntimeException: Stack is corrupted.
   at Dyalect.Runtime.DyMachine.ExecuteWithData(DyNativeFunction function, DyObject[] locals, ExecutionContext ctx) in C:\repos\source\Dyalect\feature\Dyalect\Runtime\DyMachine.cs:line 117
   at Dyalect.Runtime.DyMachine.ExecuteModule(Int32 unitId, ExecutionContext ctx) in C:\repos\source\Dyalect\feature\Dyalect\Runtime\DyMachine.cs:line 75
   at Dyalect.Runtime.DyMachine.Execute(ExecutionContext ctx) in C:\repos\source\Dyalect\feature\Dyalect\Runtime\DyMachine.cs:line 45
   at Dyalect.InteractiveContext.Eval(Boolean measureTime) in C:\repos\source\Dyalect\feature\Dyalect.Console\InteractiveContext.cs:line 99
   at Dyalect.InteractiveContext.EvalFile(String fileName, Boolean measureTime) in C:\repos\source\Dyalect\feature\Dyalect.Console\InteractiveContext.cs:line 89
   at Dyalect.Program.Main(String[] args) in C:\repos\source\Dyalect\feature\Dyalect.Console\Program.cs:line 35
```

**Comment by vorov2** [comment]
Pushed to `feature`
